Q1. A company conducted a survey of its employees and found that 70% of the employees use the
company's health insurance plan, while 40% of the employees who use the plan are smokers. What is the
probability that an employee is a smoker given that he/she uses the health insurance plan?

In [1]:
## Given that P(A) be Probability of employess using health Insurance

In [2]:
## P(A&B) be probability of employee who uses the plan are smoker

In [3]:
## P(B/A) probability of employee is a smoker given that he/she uses the health insurance plan

In [4]:
## P(A)=.7
## p(A&B)=.4
## P(B/A)=P(A&B)/P(A)=.4/.7=.571

Q2. What is the difference between Bernoulli Naive Bayes and Multinomial Naive Bayes?

In [5]:
## In Bernoulli Naive bayes assumes that  input features  can takes only 2 distinct categories/values (like 1 or 0, male or female,yes or no)

In [6]:
## While Multinomial Naive Bayes can take any disticnt categories/ countable data 

Q3. How does Bernoulli Naive Bayes handle missing values?

In [7]:
## Bernoulli Naive Bayes is a classification algorithm that is designed to work with binary or boolean data, 
## where each feature or attribute can only take on one of two possible values (e.g., 0 or 1).
## If a feature is missing or not observed for a particular data point, it is typically treated as a 0 value, which means that the feature is assumed to be absent.

Q4. Can Gaussian Naive Bayes be used for multi-class classification?

In [8]:
## Gaussian Naive Bayes can be used for multi-class classification by applying the algorithm to each class separately 
## and selecting the class with the highest probability.

Q5. Assignment:

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=pd.read_csv('spambase.data',header=None)

In [11]:
df

0     1     2    3     4     5     6     7     8     9   ...     48  \
0     0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.000   
1     0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.000   
2     0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.010   
3     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.000   
4     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.000   
...    ...   ...   ...  ...   ...   ...   ...   ...   ...   ...  ...    ...   
4596  0.31  0.00  0.62  0.0  0.00  0.31  0.00  0.00  0.00  0.00  ...  0.000   
4597  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.000   
4598  0.30  0.00  0.30  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.102   
4599  0.96  0.00  0.00  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.000   
4600  0.00  0.00  0.65  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.000   

         49   50     51     52     53     54   55    56  57  
0     0.000  0.0  0.778  0.000  0.000  3.756   61   278   1  
1     0.132  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2     0.143  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3     0.137  0.0  0.137  0.000  0.000  3.537   40   191   1  
4     0.135  0.0  0.135  0.000  0.000  3.537   40   191   1  
...     ...  ...    ...    ...    ...    ...  ...   ...  ..  
4596  0.232  0.0  0.000  0.000  0.000  1.142    3    88   0  
4597  0.000  0.0  0.353  0.000  0.000  1.555    4    14   0  
4598  0.718  0.0  0.000  0.000  0.000  1.404    6   118   0  
4599  0.057  0.0  0.000  0.000  0.000  1.147    5    78   0  
4600  0.000  0.0  0.125  0.000  0.000  1.250    5    40   0  

[4601 rows x 58 columns]

In [12]:
## Last column is spam which states whether email is spam or not
## so lets rename last column as spam

In [13]:
df=df.rename(columns={57:'spam'})

In [14]:
df.head()

0     1     2    3     4     5     6     7     8     9  ...    48  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   

      49   50     51     52     53     54   55    56  spam  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278     1  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028     1  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259     1  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191     1  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191     1  

[5 rows x 58 columns]

In [15]:
df.shape

(4601, 58)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4601 non-null   float64
 1   1       4601 non-null   float64
 2   2       4601 non-null   float64
 3   3       4601 non-null   float64
 4   4       4601 non-null   float64
 5   5       4601 non-null   float64
 6   6       4601 non-null   float64
 7   7       4601 non-null   float64
 8   8       4601 non-null   float64
 9   9       4601 non-null   float64
 10  10      4601 non-null   float64
 11  11      4601 non-null   float64
 12  12      4601 non-null   float64
 13  13      4601 non-null   float64
 14  14      4601 non-null   float64
 15  15      4601 non-null   float64
 16  16      4601 non-null   float64
 17  17      4601 non-null   float64
 18  18      4601 non-null   float64
 19  19      4601 non-null   float64
 20  20      4601 non-null   float64
 21  21      4601 non-null   float64
 22  

In [17]:
df.isnull().sum()

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
30      0
31      0
32      0
33      0
34      0
35      0
36      0
37      0
38      0
39      0
40      0
41      0
42      0
43      0
44      0
45      0
46      0
47      0
48      0
49      0
50      0
51      0
52      0
53      0
54      0
55      0
56      0
spam    0
dtype: int64

In [18]:
df['spam'].value_counts()

0    2788
1    1813
Name: spam, dtype: int64

## Model Building

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB,MultinomialNB,GaussianNB
from sklearn.model_selection import KFold

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [21]:
X=df.drop('spam',axis=1)
y=df['spam']

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=34,stratify=y)

### Bernouli Naive_Bayes

In [23]:
bnb=BernoulliNB()

In [24]:
bnb.fit(X_train,y_train)
y_pred=bnb.predict(X_test)
print("Accuracy Score: {}\n".format(accuracy_score(y_test,y_pred)))
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("\nClassification Report\n",classification_report(y_test,y_pred))

Accuracy Score: 0.8762214983713354

Confusion Matrix 
 [[517  41]
 [ 73 290]]

Classification Report
               precision    recall  f1-score   support

           0       0.88      0.93      0.90       558
           1       0.88      0.80      0.84       363

    accuracy                           0.88       921
   macro avg       0.88      0.86      0.87       921
weighted avg       0.88      0.88      0.88       921



### Multinomial Naive_Bayes

In [25]:
mnb=MultinomialNB()

In [26]:
mnb.fit(X_train,y_train)
y_pred=mnb.predict(X_test)
print("Accuracy Score: {}\n".format(accuracy_score(y_test,y_pred)))
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("\nClassification Report\n",classification_report(y_test,y_pred))

Accuracy Score: 0.7915309446254072

Confusion Matrix 
 [[455 103]
 [ 89 274]]

Classification Report
               precision    recall  f1-score   support

           0       0.84      0.82      0.83       558
           1       0.73      0.75      0.74       363

    accuracy                           0.79       921
   macro avg       0.78      0.79      0.78       921
weighted avg       0.79      0.79      0.79       921



### Guassian Naive_Bayes

In [27]:
gnb=GaussianNB()

In [28]:
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
print("Accuracy Score: {}\n".format(accuracy_score(y_test,y_pred)))
print("Confusion Matrix \n",confusion_matrix(y_test,y_pred))
print("\nClassification Report\n",classification_report(y_test,y_pred))

Accuracy Score: 0.8121606948968513

Confusion Matrix 
 [[400 158]
 [ 15 348]]

Classification Report
               precision    recall  f1-score   support

           0       0.96      0.72      0.82       558
           1       0.69      0.96      0.80       363

    accuracy                           0.81       921
   macro avg       0.83      0.84      0.81       921
weighted avg       0.86      0.81      0.81       921



### Cross Validation

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
kfold=KFold(n_splits=10)

In [31]:
### Bernoulii cross validation

In [32]:
bernouli_cv=cross_val_score(estimator=bnb,X=X_train,y=y_train,cv=kfold,scoring='accuracy')

In [33]:
bernouli_cv

array([0.86684783, 0.89945652, 0.875     , 0.88586957, 0.89673913,
       0.88586957, 0.89945652, 0.91576087, 0.88858696, 0.88043478])

In [34]:
bernouli_cv.mean()

0.8894021739130433

In [35]:
### Multinomial cross validation

In [36]:
Multinomial_cv=cross_val_score(estimator=mnb,X=X_train,y=y_train,cv=kfold,scoring='accuracy')

In [37]:
Multinomial_cv

array([0.79619565, 0.77173913, 0.78804348, 0.79891304, 0.82065217,
       0.79347826, 0.79619565, 0.80163043, 0.7826087 , 0.76630435])

In [38]:
Multinomial_cv.mean()

0.7915760869565218

In [39]:
### Guassian cross validation

In [40]:
guassian_cv=cross_val_score(estimator=gnb,X=X_train,y=y_train,cv=kfold,scoring='accuracy')

In [41]:
guassian_cv

array([0.80978261, 0.81521739, 0.76630435, 0.8423913 , 0.83152174,
       0.85869565, 0.83423913, 0.80978261, 0.80434783, 0.81521739])

In [42]:
guassian_cv.mean()

0.81875

## Conclusion

- It is found out that Bernoulli Naive Bayes is having good accuracy as well as good precision
- This reasom is beacuse output label has only two classes and data set is also small so Bernoulli works well in this data
- In email spam classification precision is very important because it is important to minimise false positive
- Because if suppose important mail is being classified as spam then it is very critial because you may miss some precious information required
- It does not matter if some spam mail is being classified as not spam becuase we can read and check that mail and manually put that