Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
X=pd.DataFrame(iris.data,columns=iris.feature_names)

In [7]:
y=iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.model_selection import  train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
KNN=KNeighborsClassifier()

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=34)

In [13]:
X_train.shape

(120, 4)

In [14]:
y_train.shape

(120,)

In [15]:
KNN.fit(X_train,y_train)

KNeighborsClassifier()

In [16]:
y_pred=KNN.predict(X_test)
print("Accuracy Score:",accuracy_score(y_test,y_pred))
print("\nConfusion Matrx :\n",confusion_matrix(y_test,y_pred))
print("\nClassification Report :\n",classification_report(y_test,y_pred))

Accuracy Score: 0.9666666666666667

Confusion Matrx :
 [[11  0  0]
 [ 0 15  0]
 [ 0  1  3]]

Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.94      1.00      0.97        15
           2       1.00      0.75      0.86         4

    accuracy                           0.97        30
   macro avg       0.98      0.92      0.94        30
weighted avg       0.97      0.97      0.96        30



Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

In [17]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
boston_data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [18]:
X=pd.DataFrame(boston_data,columns=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT'])

In [19]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [20]:
y=pd.DataFrame(target,columns=['MEDV'])

In [21]:
y.head()

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [22]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [23]:
Knn_regressor=KNeighborsRegressor()

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=34)

In [25]:
Knn_regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [26]:
y_pred=Knn_regressor.predict(X_test)

In [27]:
print("R2 Score :",r2_score(y_test,y_pred))
print("Mean Squared Error :",mean_squared_error(y_test,y_pred))
print("Mean Absolute Error :",mean_absolute_error(y_test,y_pred))

R2 Score : 0.4076917661272894
Mean Squared Error : 48.8093137254902
Mean Absolute Error : 4.685686274509804


Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
X=pd.DataFrame(iris.data,columns=iris.feature_names)
y=iris.target

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=34)

In [31]:
k_values=np.arange(1,20)
score=[]
for i in k_values:
    knn=KNeighborsClassifier(i)
    cv_score=cross_val_score(knn,X_train,y_train,cv=5)
    cv_score=np.mean(cv_score)
    score.append(cv_score)

In [32]:
score

[0.9583333333333334,
 0.9416666666666668,
 0.95,
 0.9416666666666668,
 0.9416666666666668,
 0.95,
 0.9583333333333334,
 0.9583333333333333,
 0.975,
 0.9666666666666668,
 0.9666666666666666,
 0.9583333333333334,
 0.975,
 0.975,
 0.975,
 0.9583333333333334,
 0.9583333333333334,
 0.9583333333333334,
 0.95]

In [33]:
k_values[np.argmax(score)]

9

In [34]:
## So we get the optimal value of k =9

Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [35]:
X=pd.DataFrame(boston_data,columns=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT'])
y=pd.DataFrame(target,columns=['MEDV'])

In [36]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler=StandardScaler()

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=34)

In [40]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [41]:
X_train=pd.DataFrame(X_train_scaled,columns=X.columns)
X_test=pd.DataFrame(X_test_scaled,columns=X.columns)

In [42]:
Knn_regressor=KNeighborsRegressor()

In [43]:
Knn_regressor.fit(X_train,y_train)
y_pred=Knn_regressor.predict(X_test)
print("R2 Score :",r2_score(y_test,y_pred))
print("Mean Squared Error :",mean_squared_error(y_test,y_pred))
print("Mean Absolute Error :",mean_absolute_error(y_test,y_pred))

R2 Score : 0.7428143409173108
Mean Squared Error : 21.193450980392157
Mean Absolute Error : 2.823529411764706


In [44]:
## Clearly it has been seen that score is increased by almost 35% if feature scaling is used 

Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

In [45]:
X=pd.DataFrame(iris.data,columns=iris.feature_names)
y=iris.target

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=34)

In [47]:
knn=KNeighborsClassifier(weights='distance')

In [48]:
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print("Accuracy Score:",accuracy_score(y_test,y_pred))
print("\nConfusion Matrx :\n",confusion_matrix(y_test,y_pred))
print("\nClassification Report :\n",classification_report(y_test,y_pred))

Accuracy Score: 1.0

Confusion Matrx :
 [[11  0  0]
 [ 0 15  0]
 [ 0  0  4]]

Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00         4

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Q6. Implement a function to standardise the features before applying KNN classifier.

In [49]:
def knn_classifier(X_train, X_test,y_train,y_test, k):
    # Standardize the features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    # Create a KNN classifier object with k neighbors
    knn = KNeighborsClassifier(n_neighbors=k)
    
    # Fit the classifier to the training data
    knn.fit(X_train, y_train)
    
    # Predict the classes for test set
    y_pred = knn.predict(X_test)
    accuracy=accuracy_score(y_test,y_pred)
    return accuracy

In [50]:
knn_classifier(X_train, X_test,y_train,y_test, 11)

0.9333333333333333

Q7. Write a Python function to calculate the euclidean distance between two points.

In [51]:
def Euclidean_function(x,y):
    if len(x)!=len(y):
        raise ValueError("Dimensions must be same")
    s=0
    for i,j in zip(x,y):
        
        s=(j-i)**2+s
    result=np.sqrt(s)
    return result

In [52]:
Euclidean_function((2,3),(2,5))

2.0

Q8. Write a Python function to calculate the manhattan distance between two points.

In [53]:
def manhattan_distance(x,y):
    if len(x)!=len(y):
        raise ValueError("Dimensions must be same")
    s=0
    for i ,j in zip(x,y):
        s=np.abs(j-i)+s
    return s

In [54]:
manhattan_distance((-1,3),(4,-5))

13